### ISSUE TITLE
Parse CSS error

### ISSUE THREAD

**Issue by TrySound** [yairEO/photobox#78]
Why you use two slashes here?

``` css
#pbOverlay{
    opacity:0; overflow:hidden; width:100%; height:100%; position:fixed; z-index:9999; left:0; top:0; text-align:center; pointer-events:none;
    -moz-user-select:none;
    background:rgba(0,0,0,0.90);
    // background:radial-gradient(rgba(0,0,0,.6) 0%, rgba(0,0,0,.9) 100%);
    -webkit-transform:translate3d(0px, 0px, 0px);
    -ms-transition:opacity 300ms ease;
    transition:opacity 300ms ease;
}
```
